version: '3.7'

services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: happy_db
    ports:
        - "5432:5432"