import { type NextPage } from "next";
import Head from "next/head";
import { signIn, useSession } from "next-auth/react";
import { CreateBucketList } from "../components/CreateBucketList";
import Link from "next/link";

const Home: NextPage = () => {

  const { data: session, status } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={"flex flex-col items-start"}>
        <button className={"btn btn-primary"} onClick={() => signIn()}>Login</button>
        <CreateBucketList />
        <Link href={"/bucketlists"}>
          <button className={"btn btn-secondary"}>Bucket Lists</button>
        </Link>
      </div>
    </>
  );
};

export default Home;
